targets:
  $default:
    builders:
      freezed:
        options:
          union_key: type
          union_value_case: pascal
          explicit_to_json: true
      json_serializable:
        options:
          explicit_to_json: true
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true