// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2JZxtbvpQWqxJDjw3HsUdgNXX9B29I40',
    appId: '1:160010861440:web:6770d29d102be5703f5f65',
    messagingSenderId: '160010861440',
    projectId: 'icheckit-6a8bb',
    authDomain: 'icheckit-6a8bb.firebaseapp.com',
    storageBucket: 'icheckit-6a8bb.appspot.com',
    measurementId: 'G-MZWH337QWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-a3V5oYmQDHiYhZLGlBF5XIMbxHmOtnE',
    appId: '1:160010861440:android:23fe4ff5e5807b793f5f65',
    messagingSenderId: '160010861440',
    projectId: 'icheckit-6a8bb',
    storageBucket: 'icheckit-6a8bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcmwZvnoW39UuC6qPrZXNTE8dFrQfg9I',
    appId: '1:160010861440:ios:4022fc21a10b15783f5f65',
    messagingSenderId: '160010861440',
    projectId: 'icheckit-6a8bb',
    storageBucket: 'icheckit-6a8bb.appspot.com',
    iosClientId: '160010861440-l9cf0ar8vqq6nol77iepsealrhsci51t.apps.googleusercontent.com',
    iosBundleId: 'org.nativescript.icheckitFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNcmwZvnoW39UuC6qPrZXNTE8dFrQfg9I',
    appId: '1:160010861440:ios:6f9be4ab106d3b073f5f65',
    messagingSenderId: '160010861440',
    projectId: 'icheckit-6a8bb',
    storageBucket: 'icheckit-6a8bb.appspot.com',
    iosClientId: '160010861440-qsqnikn2t55sm848cnqiit33955sdki2.apps.googleusercontent.com',
    iosBundleId: 'com.example.icheckitFinal',
  );
}
